"""Table IDs in the OSR SEO Engine base (new dedicated base).
Auto-generated by migrate_to_new_base.py.
"""

TABLE_IDS = {
    # NEW lean schema (active for v5 pipeline)
    "Batches": "tblK5u2NU4nIETJc4",
    "Articles": "tblP59vDHhGcqBsTv",
    # Legacy (to be deleted in UI by Pete)
    "Articles_Pilot": "tblu3hTGgdPbEZVaX",
    "Pillars": "tblr69WWmreSB0WrC",
    "Authors": "tblDLAf3jDetGkFhw",
    "Keyword_Patterns": "tblFElynTLv7cOiAM",
    "Dataset_Source": "tblTh9sfWStu5c5Sw",
    "Articles_Master": "tblzJ7FY66gkjw8aL",
    "Indexing_Queue": "tbl3lmJw7ewjpY6EC",
    "Keywords": "tblnxmetQeBnl8PNJ",
    "Keyword_Clusters": "tblC8IK5Bme68BCFz",
    "SERP_Snapshots": "tblnNy7XhLT0WoiQe",
    "AI_Prompts": "tblGNzWjVhJImM7L6",
}

# Active 100-article pilot table — scripts read TABLE_IDS["Articles_Master"]
TABLE_IDS["Articles_Master"] = "tblu3hTGgdPbEZVaX"  # alias to Articles_Pilot
